### ISSUE TITLE
Reference papers

### ISSUE THREAD

**Issue by HappyDay-design** [africamonkey/autopilot-cross-intersection#1]
Hello
Thank you for sharing your materials!
And I am very happy with your modified Flow. In the past, I tried to install Flow from the official repo but it always had errors. With your repo, it is easy and very fast. I do not know what you did with Flow but I am very happy to run it.
Also, I would like to ask you about reference papers related to your model. If yes, Could you please upload it?
.Thank you very much
 I am training your models 
![image](https://user-images.githubusercontent.com/82990411/192519742-42d8cacf-fa68-42da-b7cc-575a1803de3c.png)

**Comment by africamonkey** [comment]
The official repo has error because I add some new interfaces and features into the Flow such as logging summary, and use them in my code. So, if you want to run my code, you should use the modified Flow, or you will get an error. 

I forget which reference paper is related to my model. I upload them all and I hope these papers can help you. 

[1705.01196v1.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655917/1705.01196v1.pdf)
[A Painless Q-learning Tutorial (一个 Q-learning 算法的简明教程) - peghoty - 博客园.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655919/A.Painless.Q-learning.Tutorial.Q-learning.-.peghoty.-.pdf)
[A Survey of Deep Learning Techniques for Autonomous Driving.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655922/A.Survey.of.Deep.Learning.Techniques.for.Autonomous.Driving.pdf)
[Autonomous Cars - Past, Present and Future.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655923/Autonomous.Cars.-.Past.Present.and.Future.pdf)
[Belief state planning for autonomously navigating urban intersections.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655924/Belief.state.planning.for.autonomously.navigating.urban.intersections.pdf)
[CARLA An Open Urban Driving Simulator.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655925/CARLA.An.Open.Urban.Driving.Simulator.pdf)
[Congested Traffic States in Empirical Observations and Microscopic Simulations.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655928/Congested.Traffic.States.in.Empirical.Observations.and.Microscopic.Simulations.pdf)
[End to End Learning for Self-Driving Cars.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655931/End.to.End.Learning.for.Self-Driving.Cars.pdf)
[Flow - A Modular Learning Framework for Autonomy in Traffic.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655932/Flow.-.A.Modular.Learning.Framework.for.Autonomy.in.Traffic.pdf)
[Flow_Deep_Reinforcement_Learning_for_Control_in_SUMO.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655933/Flow_Deep_Reinforcement_Learning_for_Control_in_SUMO.pdf)
[Human-level control through deep reinforcement learning.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655934/Human-level.control.through.deep.reinforcement.learning.pdf)
[KL-divergence.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655937/KL-divergence.pdf)
[Microscopic Modeling of Traffic Flow- Investigation of Collision Free Vehicle Dynamics.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655938/Microscopic.Modeling.of.Traffic.Flow-.Investigation.of.Collision.Free.Vehicle.Dynamics.pdf)
[Microscopic Traffic Simulation using SUMO.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655940/Microscopic.Traffic.Simulation.using.SUMO.pdf)
[Navigating Occluded Intersections with Autonomous Vehicles Using Deep Reinforcement Learning.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655941/Navigating.Occluded.Intersections.with.Autonomous.Vehicles.Using.Deep.Reinforcement.Learning.pdf)
[Near Miss Determination Through Use of a Scale of DangerNear Miss Determination Through Use of a Scale of Danger.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655943/Near.Miss.Determination.Through.Use.of.a.Scale.of.DangerNear.Miss.Determination.Through.Use.of.a.Scale.of.Danger.pdf)
[Playing Atari with Deep Reinforcement Learning.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655945/Playing.Atari.with.Deep.Reinforcement.Learning.pdf)
[Policy gradient methods - Scholarpedia.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655946/Policy.gradient.methods.-.Scholarpedia.pdf)
[POMDP and Hierarchical Options MDP with Continuous Actions for Autonomous Driving at Intersections.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655949/POMDP.and.Hierarchical.Options.MDP.with.Continuous.Actions.for.Autonomous.Driving.at.Intersections.pdf)
[Probabilistic Risk Metrics for Navigating Occluded Intersections.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655950/Probabilistic.Risk.Metrics.for.Navigating.Occluded.Intersections.pdf)
[Proceedings_SUMO2017.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655951/Proceedings_SUMO2017.pdf)
[Proximal Policy Optimization Algorithms.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655953/Proximal.Policy.Optimization.Algorithms.pdf)
[Proximal Policy Optimization with Mixed Distributed Training.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655956/Proximal.Policy.Optimization.with.Mixed.Distributed.Training.pdf)
[Reinforcement Learning - An Introduction.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655958/Reinforcement.Learning.-.An.Introduction.pdf)
[RLlib Abstractions for Distributed Reinforcement Learning.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655959/RLlib.Abstractions.for.Distributed.Reinforcement.Learning.pdf)
[Safe Reinforcement Learning on Autonomous Vehicles.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655960/Safe.Reinforcement.Learning.on.Autonomous.Vehicles.pdf)
[Safe Reinforcement Learning with Scene Decomposition for Navigating Complex Urban Environments.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655962/Safe.Reinforcement.Learning.with.Scene.Decomposition.for.Navigating.Complex.Urban.Environments.pdf)
[siunitx.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655964/siunitx.pdf)
[statistic_id276260_number-of-fatalities-in-traffic-accidents-in-china-2007-2017.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655965/statistic_id276260_number-of-fatalities-in-traffic-accidents-in-china-2007-2017.pdf)
[TIME-TO-COLLISION_AND_COLLISION_AVOIDANCE_SYSTEMS.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655967/TIME-TO-COLLISION_AND_COLLISION_AVOIDANCE_SYSTEMS.pdf)
[Towards Full Automated Drive in Urban Environments - A Demonstration in GoMentum Station, California.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655968/Towards.Full.Automated.Drive.in.Urban.Environments.-.A.Demonstration.in.GoMentum.Station.California.pdf)
[Trust Region Policy Optimization.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655969/Trust.Region.Policy.Optimization.pdf)
[Watkins-Dayan1992_Article_Q-learning.pdf](https://github.com/africamonkey/autopilot-cross-intersection/files/9655970/Watkins-Dayan1992_Article_Q-learning.pdf)

**Comment by HappyDay-design** [comment]
Thank you for your quick reply!
But after installing Flow with your repo, I can not run some tutorials in Flow folder.

For example in Tutorial 04
![image](https://user-images.githubusercontent.com/82990411/192534057-abb68dcf-9675-4694-a0a1-92966dff9ffe.png)
 or in Tutorial 08
![image](https://user-images.githubusercontent.com/82990411/192534174-0a8a2c4f-b866-48e7-a5b1-c6681c0cbab4.png)

Maybe your modified Flow only runs with your repo
